PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX vocdata: <file:///Users/jatin/workspace/roboprof/data#>
PREFIX voc: <file:///Users/jatin/workspace/roboprof/vocabulary.ttl/schema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

SELECT DISTINCT (?course as ?courseURI) ?courseName  ?courseSubject ?courseNumber ?universityName (?university as ?universityURI) 
WHERE {
  ?university a voc:University;
              foaf:name "Concordia University" .  
  ?course a voc:Course;
          foaf:name ?courseName;
          voc:courseSubject ?courseSubject;
          voc:courseNumber ?courseNumber;
          voc:offeredBy ?university .
  ?university foaf:name ?universityName .
}

SELECT (?topic as ?topicURI) ?topicName (?courseId as ?courseURI) ?courseName ?courseSubject ?courseNumber 
WHERE {
 ?topic a voc:Topic ;
    foaf:name ?topicName ;
         foaf:name "Deep_learning" ;
         voc:TopicProvenance ?topicProvenance .
  ?lecture a voc:Lecture;
         voc:LectureContent ?topicProvenance;
         voc:BelongsTo ?courseId.
  ?courseId a voc:Course;
        foaf:name ?courseName;
       voc:courseSubject ?courseSubject;
      voc:courseNumber ?courseNumber.    
}

SELECT  (?topic as ?topicURI) ?topicName (?course as ?courseURI) ?courseName (?lectures as ?lectureURI) ?lectureNumber
WHERE {
  ?course a voc:Course;
    foaf:name ?courseName;
  foaf:name "APPLIED ARTIFICIAL INTELLIGENCE".
  
  ?lectures voc:BelongsTo ?course;
    voc:LectureNumber ?lectureNumber;
    voc:LectureContent ?lectureContent.
  
  ?topic a voc:Topic;
    voc:TopicProvenance ?lectureContent;
    foaf:name ?topicName.
    FILTER(?lectureNumber = "7")
}

SELECT DISTINCT ?courseName (?courseId as ?courseURI) ?courseSubject ?courseNumber
WHERE {
  ?university foaf:name "Concordia University" . 
  
  ?courseId a voc:Course;
            voc:offeredBy ?university;
            voc:courseSubject ?courseSubject;
            foaf:name ?courseName;
            voc:courseNumber ?courseNumber .
  
  FILTER(?courseSubject = "COMP")
}

SELECT  (?topic as ?topicURI) ?topicName (?course as ?courseURI) ?courseNo  ?materials
WHERE {
  ?course a voc:Course;
          voc:courseSubject "COMP";
          voc:courseNumber "6721";
          foaf:name ?courseName;
          voc:courseSubject ?courseSub;
          voc:courseNumber ?courseNum.
  
    ?lecture a voc:Lecture;
      foaf:name ?lectureName ;
      voc:LectureContent ?lectureContent;
      voc:BelongsTo ?course;
      voc:LectureContent ?materials.
  
  ?topic a voc:Topic;
      foaf:name ?topicName;
      foaf:name "Deep_learning";
      voc:TopicProvenance ?lectureContent;
  BIND(CONCAT(?courseSub, " ", ?courseNum) AS ?courseNo)
}

SELECT (?course as ?courseURI) ?courseName ?courseSubject ?courseNumber ?description ?credits
WHERE {
  ?course a voc:Course;
          foaf:name ?courseName;
          voc:courseSubject ?courseSubject;
          voc:courseNumber ?courseNumber;
          voc:courseDescription ?description;
          voc:courseCredits ?credits.
          
  FILTER(?courseSubject = "COMP" && ?courseNumber = "6741")
}

SELECT  DISTINCT (?course as ?courseURI) ?courseNo  ?additionalResources 
WHERE {
  ?course a voc:Course;
          voc:courseSubject "COMP";
          voc:courseNumber "6741";
          foaf:name ?courseName;
          voc:courseSubject ?courseSub;
          voc:courseNumber ?courseNum.
  
    ?lecture a voc:Lecture;
      foaf:name ?lectureName ;
      voc:LectureContent ?lectureContent;
      voc:BelongsTo ?course;
      voc:LectureContent ?additionalResources.  
    ?additionalResources a voc:AdditionalResources.
  
  
  BIND(CONCAT(?courseSub, " ", ?courseNum) AS ?courseNo)
}

SELECT (?course as ?courseURI) ?courseNo (?lecture as ?lectureURI) ?lectureName ?lectureNumber ?lectureContent
WHERE {
  ?course a voc:Course ;
          voc:courseSubject "COMP" ;
          voc:courseNumber "6721" ;
          voc:courseSubject ?courseSub;
          voc:courseNumber ?courseNum.
  
  ?lecture a voc:Lecture ;
           voc:BelongsTo ?course ;
           voc:LectureNumber "11";
           voc:LectureNumber ?lectureNumber;
           foaf:name ?lectureName;
           voc:LectureContent ?lectureContent.
  BIND(CONCAT(?courseSub, " ", ?courseNum) AS ?courseNo)
}

SELECT  (?topic as ?topicURI) ?topicName (?course as ?courseURI) ?courseNo  ?readingMaterials
WHERE {
  ?course a voc:Course;
          voc:courseSubject "COMP";
          voc:courseNumber "6721";
          foaf:name ?courseName;
          voc:courseSubject ?courseSub;
          voc:courseNumber ?courseNum.
  
    ?lecture a voc:Lecture;
      foaf:name ?lectureName ;
      voc:LectureContent ?lectureContent;
      voc:BelongsTo ?course;
      voc:LectureContent ?readingMaterials.
      ?readingMaterials a voc:Readings.
  
  ?topic a voc:Topic;
      foaf:name ?topicName;
      foaf:name "Deep_learning";
      voc:TopicProvenance ?lectureContent;
  BIND(CONCAT(?courseSub, " ", ?courseNum) AS ?courseNo)
}

SELECT DISTINCT ?course ?competency (?topic as ?competencyURI)
WHERE {
  ?student a voc:Student ;
           voc:Competency ?competencyNode .
  ?competencyNode voc:Course ?course ;
            voc:competencies ?competency .
  ?topic a voc:Topic;
            foaf:name ?competency.
  FILTER(?course = "COMP6741")
}

SELECT DISTINCT (?student as ?studentURI) ?IDnumber ?givenName ?familyName ?course ?grade 
WHERE {
  ?student a voc:Student;
           voc:IDNumber "123456";      
           voc:CompletedCourse ?completedCourse.
  
  ?completedCourse voc:Course ?course ;                   
                   voc:Grade ?grade .
  
  ?student foaf:givenName ?givenName ;
           foaf:familyName ?familyName ;
           voc:IDNumber ?IDnumber.
  
  FILTER (?course = "COMP6741")
}

SELECT DISTINCT (?student as ?studentURI) ?studentID ?givenName ?familyName ?email
WHERE {
  ?student a voc:Student;
           voc:CompletedCourse ?completedCourse;
           foaf:givenName ?givenName;
           foaf:familyName ?familyName;
           voc:IDNumber ?studentID;
           foaf:mbox ?email.
   ?completedCourse voc:Course ?course ;
           
  FILTER(?course = "COMP6741")
}

SELECT DISTINCT ?course ?grade ?alphabeticPrefix ?numericPart (?course1 as ?courseURI)
WHERE {
  ?student a voc:Student;
           voc:IDNumber "123456";      
           voc:CompletedCourse ?completedCourse.
  
  ?completedCourse voc:Course ?course ;
                    voc:Grade ?grade .
  BIND(REPLACE(STR(?course), "[^A-Za-z]+", "") AS ?alphabeticPrefix).
  BIND(REPLACE(STR(?course), "[^0-9]+", "") AS ?numericPart).
  
  ?course1 a voc:Course;
              voc:courseNumber ?numericPart;
              voc:courseSubject ?alphabeticPrefix;
              voc:courseDescription "Lecture".
  }

SELECT (COUNT(*) AS ?totalTriples)
  WHERE {
    ?subject ?predicate ?object
  }

SELECT (COUNT(DISTINCT ?course) AS ?courseCount)
WHERE {
  ?course a voc:Course .
}